### ISSUE TITLE
Add support for enum keys in maps

### ISSUE THREAD

**Issue by PixelBumper** [inspire-software/geda-genericdto#3]
Currently it is not possible to have enum keys in Maps, as unfortunately GeDA expects an entry in the beanfactory that instantiates an enum.

In case I just missed how to create the assembler, how do I configure the mapping correctly?

```java
public enum SomeEnum{
	VALUE_A,
	VALUE_B
}

class Entity{
	private Map<SomeEnum, Long> map;
	// getter /setter
}

@Dto
class MapDto(){

	/* what should go in here?*/
	@DtoMap
	private Map<SomeEnum, Long> map;
	//getter setter
}
//...
final Entity entity = new Entity();
final MapDto dto = new MapDto();
DTOAssembler.newAssembler(MapDto.class, Map.class).assembleDto(dto, entity, null, null);
//...


```

**Comment by denyspavlov** [comment]
You have an field on entity which is map of immutable objects and the same on the DTO. So in terms of mapping just think of it as "copy by reference". This means you do not need @DtoMap but rather @DtoField. @DtoMap is only used when you have complex sub entities relationships (e.g. like RDBMS with sub entities mapped as map in ORM).

So just try this:
```
@Dto
class MapDto(){

	@DtoField
	private Map<SomeEnum, Long> map;
	//getter setter
}
```

**Comment by PixelBumper** [comment]
Worked thanks :)
