### ISSUE TITLE
Geda does not recognize chainable setters (those returning 'this', not void)

### ISSUE THREAD

**Issue by citDennis** [inspire-software/geda-genericdto#5]
Our codebase uses chainable setters a lot and it would be really great if Geda could support them. As it is now it requires a lot of refactoring to implement.

I get:
com.inspiresoftware.lib.dto.geda.exception.InspectionPropertyNotFoundException: Unable to locate field 'No write method for: #customerNumber'
	at unit_tests.bo.CustomerBOTranslatorTest.test_transfer(CustomerBOTranslatorTest.java:19)

Setter in question:
public Customer setCustomerNumber(Integer customerNumber){
    this.customerNumber = customerNumber;
    return this;
}

I couldn't find this in the documentation. I hope you would consider allowing Geda to recognize our setters!

[Updated to show the setters are of course declared public]

**Comment by inspire-software** [comment]
Hi,

GeDA uses void setters as this is the specification for the POJO beans. Your configuration does not follow POJO spec. Usually to conform to POJO spec your domain should have normal get/set and then a chain method named after property.

```
public Integer getCustomerNumber() {
   return this.customerNumber;
}

public void setCustomerNumber(Integer customerNumber){
   this.customerNumber = customerNumber;
}

public Customer customerNumber(Integer customerNumber){
  this.customerNumber = customerNumber;
  return this;
}
```

I fully understand your point about the refactoring but scanning methods just by name can lead to unpredictable behaviour. Consider that someone would add the following methods:

```
public Customer setCustomerNumber(Integer customerNumber){
this.customerNumber = customerNumber;
return this;
}

public void setCustomerNumber(Long customerNumber){
this.customerNumber = customerNumber;
return this;
}


public Date setCustomerNumber(Date customerNumber){
this.customerNumber = customerNumber.getTime();
return customerNumber;
}
```

Example above shows how there could be many different method signatures and it would require complex logic to determine correct one. Not only this may lead to unpredictable behaviour (i.e. which is the right one to choose?) but also it will have performance implications. That is why GeDA strictly follows the POJO bean spec.

**Comment by citDennis** [comment]
Thanks for the quick reply! Unfortunately it was the answer I was afraid of getting. I suppose, configuration being evil and more code being less performance, you wouldn't consider adding a configurable setting for cases such as ours, of which there are many out there these days?

**Comment by inspire-software** [comment]
Can you prepare a JUnit test suite for your case and send it to us to see exactly what behaviour is needed? Then we can review it and see what can be done.

**Comment by citDennis** [comment]
Thank you so much for your consideration! 
I wrote a basic test that consists of two tests, one passing test that uses an object with standard setters, and a failing test that demonstrates the error and the "chained setters" coding style. 
If this were to work we could use Lombok and Geda together, as it is now this is 'do-able' but requires persistence and a lot of truly maddening re-work.
[GedaTest.zip](https://github.com/inspire-software/geda-genericdto/files/1894667/GedaTest.zip)

**Comment by inspire-software** [comment]
Thank you for feedback. Hopefully we will have some time to look at it closer to end of this week.

**Comment by inspire-software** [comment]
Hi,

We have done some improvements to property inspector. Everything is committed to branch https://github.com/inspire-software/geda-genericdto/tree/feature_chained_setter

Could you have a go at it and see how it behaves. So far tests are passing but would be good to receive feedback from use on an actual project.

**Comment by citDennis** [comment]
One word: Awesome! 
I built it, spent this morning testing it on our development version and even deployed it on our Artifactory. 
No problems whatsoever, it works beautifully with Lombok's @Accessors(chain = true), giving us 100% compatibility with our existing code base. We now have a clear path to cleaner and leaner code, with no more painful refactoring. 
I am looking forward to the next release so we can pick up the normal Maven release again. 
Thank you very much for your speedy help!

**Comment by citDennis** [comment]
We ran into trouble with Artifactory yesterday and had to revert :-( 
We really hope you will be able to release these enhancements with the new version soon, so we can pick up the official release. If you could relese a "prerelease"or "alpha" or some such version via maven we'd pick it up ASAP! Testing on a local build worked well and no problems were encountered. I spent four solid hours refactoring and the Geda worked flawlessly. The remaining problem has got to be in the way I deployed to Artifactory.

**Comment by inspire-software** [comment]
3.1.2 is now available in maven central.

**Comment by citDennis** [comment]
Inspire, thank you so much! I was away on vacation last week but my colleagues picked it up as soon as they saw the release. What a way to start work after a vacation. Inspiring indeed!
