### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by a343** [inspire-software/geda-genericdto#7]
Hello, 

Geda-genericdto use slf4j-log4j12 library and that library depends on log4j one, that is vulnerable. Please, could you update to use another to avoid these vulnerablities ?

![image](https://user-images.githubusercontent.com/4516813/108849152-217f9480-75e2-11eb-89ea-e841b7151a77.png)

![image](https://user-images.githubusercontent.com/4516813/108849207-30664700-75e2-11eb-8a50-7bb45634db98.png)

"Please note that Log4j 1.x has reached end of life and is no longer supported. Vulnerabilities reported after August 2015 against Log4j 1.x were not checked and will not be fixed. Users should upgrade to Log4j 2 to obtain security fixes."

Thanks

**Comment by inspire-software** [comment]
Version 3.2.0 has been released to address above issues

https://search.maven.org/artifact/com.inspire-software.lib.dto.geda/geda/3.2.0/pom
